// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: RadioweckerAI

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_homeScreen
extern void ui_homeScreen_screen_init(void);
extern void ui_homeScreen_screen_destroy(void);
extern lv_obj_t * ui_homeScreen;
extern lv_obj_t * ui_homeScreenPanel;
extern lv_obj_t * ui_StatusBar;
extern lv_obj_t * ui_ipLabel;
extern lv_obj_t * ui_wifiQualityLabel;
extern lv_obj_t * ui_wifiLabel;
extern lv_obj_t * ui_timePanel;
extern lv_obj_t * ui_CurrentDate;
extern lv_obj_t * ui_CurrentTime;
extern lv_obj_t * ui_NextAlarm;
extern lv_obj_t * ui_sensorPanel;
extern lv_obj_t * ui_ContSensorTitles;
extern lv_obj_t * ui_ContTempTitle;
extern lv_obj_t * ui_tempTitle;
extern lv_obj_t * ui_ContHumTitle;
extern lv_obj_t * ui_humTitle;
extern lv_obj_t * ui_ContCo2Title;
extern lv_obj_t * ui_co2Title;
extern lv_obj_t * ui_ContTvocTitle;
extern lv_obj_t * ui_tvocTitle;
extern lv_obj_t * ui_ContSensorValues;
extern lv_obj_t * ui_ContTempLabel;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_ContHumLabel;
extern lv_obj_t * ui_humidityLabel;
extern lv_obj_t * ui_ContCo2Label;
extern lv_obj_t * ui_eco2Label;
extern lv_obj_t * ui_ContTvocLabel;
extern lv_obj_t * ui_tvocLabel;
extern lv_obj_t * ui_weatherPanel;
extern lv_obj_t * ui_ContCurrentWeather;
extern lv_obj_t * ui_currentWeatherPanel;
extern lv_obj_t * ui_currentWeatherTitle;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_currentTempLabel;
extern lv_obj_t * ui_feelsLikeLabel;
extern lv_obj_t * ui_weatherDescLabel;
extern lv_obj_t * ui_contForecast;
extern lv_obj_t * ui_morningPanel;
extern lv_obj_t * ui_morningTitle;
extern lv_obj_t * ui_morningIcon;
extern lv_obj_t * ui_morningTempLabel;
extern lv_obj_t * ui_morningRainLabel;
extern lv_obj_t * ui_afternoonPanel;
extern lv_obj_t * ui_afternoonTitle;
extern lv_obj_t * ui_afternoonIcon;
extern lv_obj_t * ui_afternoonTempLabel;
extern lv_obj_t * ui_afternoonRainLabel;
extern lv_obj_t * ui_nightPanel;
extern lv_obj_t * ui_nightTitle;
extern lv_obj_t * ui_nightIcon;
extern lv_obj_t * ui_nightTempLabel;
extern lv_obj_t * ui_nightRainLabel;
extern void ui_event_Container1(lv_event_t * e);
extern lv_obj_t * ui_Container1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_homeScreen;
extern lv_obj_t * uic_homeScreenPanel;
extern lv_obj_t * uic_StatusBar;
extern lv_obj_t * uic_ipLabel;
extern lv_obj_t * uic_wifiQualityLabel;
extern lv_obj_t * uic_wifiLabel;
extern lv_obj_t * uic_timePanel;
extern lv_obj_t * uic_CurrentDate;
extern lv_obj_t * uic_CurrentTime;
extern lv_obj_t * uic_NextAlarm;
extern lv_obj_t * uic_sensorPanel;
extern lv_obj_t * uic_ContSensorTitles;
extern lv_obj_t * uic_ContTempTitle;
extern lv_obj_t * uic_tempLabel;
extern lv_obj_t * uic_ContHumTitle;
extern lv_obj_t * uic_humTitle;
extern lv_obj_t * uic_ContCo2Title;
extern lv_obj_t * uic_co2Title;
extern lv_obj_t * uic_ContTvocTitle;
extern lv_obj_t * uic_tvocTitle;
extern lv_obj_t * uic_ContSensorValues;
extern lv_obj_t * uic_ContTempLabel;
extern lv_obj_t * uic_tempLabel;
extern lv_obj_t * uic_ContHumLabel;
extern lv_obj_t * uic_humidityLabel;
extern lv_obj_t * uic_ContCo2Label;
extern lv_obj_t * uic_eco2Label;
extern lv_obj_t * uic_ContTvocLabel;
extern lv_obj_t * uic_tvocLabel;
extern lv_obj_t * uic_weatherPanel;
extern lv_obj_t * uic_ContCurrentWeather;
extern lv_obj_t * uic_currentTempLabel;
extern lv_obj_t * uic_feelsLikeLabel;
extern lv_obj_t * uic_weatherDescLabel;
extern lv_obj_t * uic_morningPanel;
extern lv_obj_t * uic_morningTitle;
extern lv_obj_t * uic_morningIcon;
extern lv_obj_t * uic_morningTempLabel;
extern lv_obj_t * uic_afternoonPanel;
extern lv_obj_t * uic_afternoonTitle;
extern lv_obj_t * uic_afternoonIcon;
extern lv_obj_t * uic_afternoonTempLabel;
extern lv_obj_t * uic_afternoonRainLabel;
extern lv_obj_t * uic_nightPanel;
extern lv_obj_t * uic_nightTitle;
extern lv_obj_t * uic_nightIcon;
extern lv_obj_t * uic_nightTempLabel;
extern lv_obj_t * uic_nightRainLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

